@BASEURL = http://localhost:9000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU3NDU4MDEzfQ.XSjrxOHTQ5vRQwNns93n4yOC3BwRXg_GaraPFHwUDcE

### Register User
POST {{BASEURL}}/api/v1/user/register
Content-Type: application/json
Accept: application/json

{
    "username": "TESTUSER",
    "email": "testuser@email.com",
    "password": "password123",
    "firstName": "ANYA",
    "middleName": "",
    "lastName": "FORGER",
    "birthdate": "07/09/2002",
    "address": "128 Park Avenue, West Berlint",
    "brgy": "brgy One",
    "municipality": "General Trias",
    "province": "Cavite",
    "department": "department"
}

### Login User
POST {{BASEURL}}/api/v1/user/login
Content-Type: application/json
Accept: application/json

{
    "userAccess": "testuser@email.com",
    "password": "password123"
}

### Get All User
GET {{BASEURL}}/api/v1/user/get-all
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Get Current User
GET {{BASEURL}}/api/v1/user/get-current
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Delete User
DELETE {{BASEURL}}/api/v1/user/delete/:userId
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

### Create Queue
POST {{BASEURL}}/api/v1/queue/create
Content-Type: application/json
Accept: application/json

{
    "email": "testuser@email.com",
    "password": "password123",
    "firstName": "ANYA",
    "middleName": "",
    "contact_number": "09101234567",
    "lastName": "FORGER",
    "birthdate": "07/09/2002",
    "address": "128 Park Avenue, West Berlint",
    "brgy": "brgy One",
    "municipality": "General Trias",
    "province": "Cavite",
    "department": "department",
    "visit_purpose": "test visit"
}

### Update Queue
PUT {{BASEURL}}/api/v1/queue/update/001
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "department": "department",
    "status": "on queue"
}

### Get All Pending Queue
GET {{BASEURL}}/api/v1/queue/get-all-pending
Content-Type: application/json
Accept: application/json

### Get All Queue By Department
GET {{BASEURL}}/api/v1/queue/get-all
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}